
default:usage

compile_all:
	@cd ./src/CPU_GPU_DGEMM; make; 
	@cd ..;
	@cd ..
	
usage:
	@echo "                                                                            "            
	@echo "        ......................................................................"
	@echo "           Usage :     make compile_all					" 
	@echo "                   View README file before using make"
	@echo "        ......................................................................."
 
clean:
	@cd ./src/CPU_GPU_DGEMM;make clean; 
	@cd ..;
	@cd ..
