
####################Makefile for mpi-io-multiple-files#################################### 

#OBJECT = mpi-io-multiple-files
OBJECT = mpi-io-par-read-multiple-files

run:
	mpicc -o run $(OBJECT).c

clean:
	rm run 
