#
#
# *******************************************************************
#
#		C-DAC Tech Workshop : hyPACK-2013
#                           October 15-18, 2013
#
# *******************************************************************
#   Created             : August 2013
#
#   E-mail              : hpcfte@cdac.in     
#
default:usage

compile_all:
	@cd ./src/Project-Mflops-GPU; make; 
	@cd ..;
	@cd ..
	
usage:
	@echo "                                                                            "            
	@echo "        ......................................................................"
	@echo "           Usage :     make compile_all					" 
	@echo "                   View README file before using make"
	@echo "        ......................................................................."
 
clean:
	@cd ./src/Project-Mflops-GPU;make clean; 
	@cd ..;
	@cd ..
