
       integer ROW_SIZE_A, COL_SIZE_A, ROW_SIZE_B, COL_SIZE_B
       integer TOTAL_SIZE_A, TOTAL_SIZE_B
       integer TOTAL_SIZE_C, NDIMENSIONS

       PARAMETER(ROW_SIZE_A=9, COL_SIZE_A=9)
       PARAMETER(ROW_SIZE_B=9, COL_SIZE_B=9) 

       PARAMETER(TOTAL_SIZE_A=ROW_SIZE_A*COL_SIZE_A)
       PARAMETER(TOTAL_SIZE_B=ROW_SIZE_B*COL_SIZE_B)

       PARAMETER(TOTAL_SIZE_C=ROW_SIZE_A*COL_SIZE_B, NDIMENSIONS=2)

