#
#   C-DAC Tech Workshop - 2013
#      Oct 15 - 18, 2013
#
#
#

CC = icc

CFLAGS = -std=c99 -openmp

LIBS	= -mkl
SRC	=  matrix-matrix-addition-opemp-mic-offload-memory-alignment.c

all	: run

run	: $(SRC)
	$(CC) $(CFLAGS) -o $@ $(SRC) $(LIBS)

clean	:
	rm -f *.o *.out run
