        integer VECTOR_SIZE, MATRIX_SIZE, TOTAL_SIZE, MAX_NONZEROS
	integer MAX_PROCS 
	real    SPARSITY, EPSILON
	parameter (VECTOR_SIZE = 28, MATRIX_SIZE = 28)
	parameter (TOTAL_SIZE = MATRIX_SIZE*MATRIX_SIZE) 
	parameter (MAX_NONZEROS = TOTAL_SIZE, MAX_PROCS = 8)
	parameter (SPARSITY = 0.60, EPSILON = 1.0E-05 )
